### PR TITLE
update flake.lock

### PR DESCRIPTION
**Pull request by sheepforce**
Update of flake.lock. Contains changes from https://github.com/NixOS/nixpkgs/pull/299273 and is prerequisite for #417 

Failing packages:

  * [x] [crest](https://nix-qchem-hydra.fysik.su.se//build/134986) (fixed by #417)
  * [x] [dftbplus](https://nix-qchem-hydra.fysik.su.se//build/134870) (fixed by #417)
  * [x] [gator](https://nix-qchem-hydra.fysik.su.se//build/134763) (fixed by #417)
  * [x] [veloxchem](https://nix-qchem-hydra.fysik.su.se//build/134894) (fixed by #417)
  * [x] [xtb-python](https://nix-qchem-hydra.fysik.su.se//build/134603) (fixed by #417)
  * [x] [xtb](https://nix-qchem-hydra.fysik.su.se//build/134670) (fixed by #417)

### CODE REVIEW

**Comment by sheepforce** [comment]
DFTB+ is not fun. It strictly requires all the CMake files of all the tight binding dependencies, so simple-dftd3, dftd4, mstore, mctc-lib, tblite, ...

They mostly use git submodules to vendor them, which makes it easier but less nice for packaging. Then only test-drive is missing ...

Alternatively I could disable the tblite and dispersion functionality of DFTB+ which seems like a very hard compromise.

**Comment by sheepforce** [comment]
Hydra is all green for #417 into this branch. https://nix-qchem-hydra.fysik.su.se//jobset/NixOS-QChem-PRs/PR-head-417

**Comment by markuskowa** [comment]
pysisyphus still fails some tests:
```
=========================== short test summary info ============================
FAILED tests/test_davidson/test_davidson.py::test_block_davidson_acet[True-2-1692.14866799] - assert 1 == 2
FAILED tests/test_davidson/test_davidson.py::test_block_davidson_acet[False-4-1692.1484062] - assert 3 == 4
FAILED tests/test_modekill/test_modekill.py::test_modekill_xtb - AssertionError: 
FAILED tests/test_xtb/test_xtb.py::test_xtb_hessian - assert -570.1506220954086 == -572.1710873 ± 5.7e-04
= 4 failed, 762 passed, 197 skipped, 357 deselected, 14 xfailed, 104 warnings in 1117.81s (0:18:37) =
```

**Comment by sheepforce** [comment]
> pysisyphus still fails some tests:

now also fixed in #417

**Comment by markuskowa** [comment]
I actually have hard time verifying that everything builds. Both PRs show broken builds. When I try to build the flake-update branch itself crest etc. are still broken. Can you please merge  https://github.com/Nix-QChem/NixOS-QChem/pull/417 into this PR, then we get one clear answer.

**Comment by sheepforce** [comment]
Is merged now

**Comment by markuskowa** [comment]
pysisyphus still fails the same tests.

**Comment by sheepforce** [comment]
Argh, yes. Because I didn't push the fix :( Here it is.

**Comment by markuskowa** [comment]
Yes, now it everything builds again.
Thanks for fixing everything.

**Pull request merged**
