### PR TITLE
Staging, Update flake.lock

### PR DESCRIPTION
**Pull request by markuskowa**
Packages that still need fixing:
* [x] wxmacmolplt, Runs into linker problems
```
/nix/store/74y3751gsixaz9797ib0hp7c658sp1y5-binutils-2.40/bin/ld: glew.o: undefined reference to symbol 'glXGetProcAddressARB'
/nix/store/74y3751gsixaz9797ib0hp7c658sp1y5-binutils-2.40/bin/ld: /nix/store/v8dsxqva19dfz8p92spjplb3j5j2b1zy-libglvnd-1.6.0/lib/libGL.so.1: error adding symbols: DSO missing from command line
```
* [ ] cclib, see https://github.com/Nix-QChem/NixOS-QChem/pull/346

### CODE REVIEW

**Comment by sheepforce** [comment]
For wxmacmolplt see https://github.com/NixOS/nixpkgs/pull/259212

**Comment by sheepforce** [comment]
Would be great if could get 
https://github.com/NixOS/nixpkgs/pull/259241
and
https://github.com/NixOS/nixpkgs/pull/259235
also in. They are required for the Psi4 1.8.2 update.

**Comment by markuskowa** [comment]
> Would be great if we could get
> [NixOS/nixpkgs#259241](https://github.com/NixOS/nixpkgs/pull/259241)
> and
> [NixOS/nixpkgs#259235](https://github.com/NixOS/nixpkgs/pull/259235)
> in. They are required for the Psi4 1.8.2 update.

We need another round of flake.lock updates for `wxmacmolplt` anyway. I am afraid though that is another mass rebuild on nixpkgs-unstable waiting that brings new issues to fix.

**Comment by markuskowa** [comment]
All green.

**Pull request merged**
