### PR TITLE
psi4: split output -> out, dev

### PR DESCRIPTION
**Pull request by markuskowa**
.dev is 33M large (libint headers)!

### CODE REVIEW

**Comment by sheepforce** [comment]
Hm, we already had this attempt and it broke Psi4; see here and here

  * https://github.com/Nix-QChem/NixOS-QChem/issues/379
  * https://github.com/Nix-QChem/NixOS-QChem/pull/380

**Comment by markuskowa** [comment]
> Hm, we already had this attempt and it broke Psi4; see here and here
> 
> * [Psi4 fails with missing python deps #379](https://github.com/Nix-QChem/NixOS-QChem/issues/379)
> * [psi4: do not split output #380](https://github.com/Nix-QChem/NixOS-QChem/pull/380)

Groundhog day... However, it does not seem to break PSi4 any longer. I can run the build on a test input e.g. `result/bin/psi4 test.inp` executes just fine.

**Comment by sheepforce** [comment]
Could you also try if `nix shell .#psi4` and `nix run .#psi4 -- -i test.inp` work? These were some funny problems last time. If both do work, then fine for me :)

**Comment by markuskowa** [comment]
Yep, ok. That is still broken. "Great" that that the new interface behaves differently.

**Pull request closed without merging**
