### PR TITLE
staging: update flake.lock

### PR DESCRIPTION
**Pull request by markuskowa**
Using staging here because the following packages are broken on nixpkgs-unstable:

* [x] polyply
* [x] python3.xtb-python
* [x] python3.pyscf (broken upstream)
* [ ] pysisyphus

### CODE REVIEW

**Comment by sheepforce** [comment]
>     * [ ]  polyply

Fixed by #319

>    * [ ] python3.xtb-python

Fixed by #320

**Comment by sheepforce** [comment]
Would be gread if we could also include https://github.com/NixOS/nixpkgs/pull/249709 in this update

**Comment by sheepforce** [comment]
Hydra is fully green now: https://nix-qchem-hydra.fysik.su.se//eval/233895#tabs-still-succeed

**Comment by markuskowa** [comment]
Yes, but on the unfree Hydra `pysisyphus` now fails it's Orca tests:
```
=========================== short test summary info ============================
FAILED tests/test_adaptive_neb/test_adaptive_neb.py::test_anapot_aneb - ValueError: 'x0' must only have one dimension.
FAILED tests/test_adaptive_neb/test_adaptive_neb.py::test_hcn_aneb - ValueError: 'x0' must only have one dimension.
FAILED tests/test_helpers/test_helpers.py::test_align_coords_interpolate - ValueError: 'x0' must only have one dimension.
FAILED tests/test_integrals/test_integrals.py::test_orca_spherical_overlaps[orca_ch4_def2svp.json] - AssertionError: 
FAILED tests/test_integrals/test_integrals.py::test_orca_spherical_overlaps[orca_ch4_sto3g.json] - AssertionError: 
FAILED tests/test_integrals/test_integrals.py::test_orca_spherical_overlaps[orca_ch4_tzvpp.json] - AssertionError: 
FAILED tests/test_integrals/test_integrals.py::test_orca_spherical_overlaps[orca_ch4_qzvpp.json] - AssertionError: 
FAILED tests/test_integrals/test_integrals.py::test_orca_one_el_integrals[orca_h2o_sto3g.json] - AssertionError: 
FAILED tests/test_integrals/test_integrals.py::test_orca_one_el_integrals[orca_h2o_def2svp.json] - AssertionError: 
FAILED tests/test_integrals/test_integrals.py::test_fchk_overlaps[g16_ch4_qzvpp.fchk] - AssertionError: 
FAILED tests/test_interpolate/test_interpolate.py::test_ala_dipeptide_interpol[LST] - ValueError: 'x0' must only have one dimension.
FAILED tests/test_orca/test_orca.py::test_orca_gs_densities[orca_ch4_sto3g_rhf.densities-orca_ch4_sto3g_rhf.json] - AssertionError
FAILED tests/test_orca/test_orca.py::test_orca_gs_densities[orca_ch4_sto3g_uhf.densities-orca_ch4_sto3g_uhf.json] - AssertionError
FAILED tests/test_orca/test_orca.py::test_orca_es_densities[orca_ch4_sto3g_rhf_cis.densities-orca_ch4_sto3g_rhf_cis.json-ref_dpm0] - AssertionError
FAILED tests/test_orca/test_orca.py::test_orca_es_densities[orca_ch4_sto3g_uhf_cis.densities-orca_ch4_sto3g_uhf_cis.json-ref_dpm1] - AssertionError
FAILED tests/test_overlap_calculator/test_top.py::test_top_differences - AssertionError
FAILED tests/test_wavefunction/test_localization.py::test_pipek_mezey - AssertionError
FAILED tests/test_wavefunction/test_localization.py::test_foster_boys - AssertionError
FAILED tests/test_wavefunction/test_multipoles.py::test_transition_multipole_moments[00_pyrrole_rhf-False] - AssertionError
FAILED tests/test_wavefunction/test_multipoles.py::test_transition_multipole_moments[01_pyrrole_uhf-True] - AssertionError
FAILED tests/test_wavefunction/test_shell.py::test_pyscf_shells - AssertionError: 
FAILED tests/test_wavefunction/test_shell.py::test_grid_density - AssertionError: 
FAILED tests/test_wavefunction/test_shell.py::test_quadrupole_ints - AssertionError: 
FAILED tests/test_wavefunction/test_shell.py::test_2c2e - AssertionError: 
FAILED tests/test_wavefunction/test_shell.py::test_3c2e - AssertionError: 
FAILED tests/test_wavefunction/test_wavefunction.py::test_orca_json[orca_ch4_sto3g.json-False] - AssertionError
FAILED tests/test_wavefunction/test_wavefunction.py::test_orca_json[orca_ch4_sto3g_uhf.json-True] - AssertionError
FAILED tests/test_wavefunction/test_wavefunction.py::test_orca_mulliken[orca_ch4_sto3g.json] - AssertionError
FAILED tests/test_wavefunction/test_wavefunction.py::test_orca_mulliken[orca_ch4_sto3g_uhf.json] - AssertionError
FAILED tests/test_wavefunction/test_wavefunction.py::test_orca_iao[iao_ref.json] - AssertionError
FAILED tests/test_wavefunction/test_wavefunction.py::test_orca_iao[iao_ref_uhf.json] - AssertionError
FAILED tests/test_wavefunction/test_wavefunction.py::test_orca_dipole_moments[orca_dipmom.json-ref_dip_mom0] - AssertionError
FAILED tests/test_wavefunction/test_wavefunction.py::test_orca_dipole_moments[orca_dipmom_uhf.json-ref_dip_mom1] - AssertionError
FAILED tests/test_wavefunction/test_wavefunction.py::test_mulliken_exc - AssertionError
FAILED tests/test_wavefunction/test_wavefunction.py::test_orca_unrestricted - AssertionError
FAILED tests/test_wavefunction/test_wavefunction.py::test_orca_ecp[0-ecp_electrons0] - AssertionError
FAILED tests/test_wavefunction/test_wavefunction.py::test_orca_ecp[0-ecp_electrons1] - AssertionError
FAILED tests/test_wavefunction/test_wavefunction.py::test_quadrupole_moment - AssertionError
FAILED tests/test_wavefunction/test_wavefunction.py::test_one_el_terms - AssertionError
FAILED tests/test_wavefunction/test_wavefunction.py::test_eval_esp - AssertionError
= 40 failed, 710 passed, 189 skipped, 356 deselected, 14 xfailed, 15473 warnings in 2189.66s (0:36:29) =
```

**Pull request merged**
