### PR TITLE
update package list

### PR DESCRIPTION
**Pull request by markuskowa**
A task that screams "automation!"

### CODE REVIEW

**Comment by sheepforce** [comment]
For JSON this should be easy using `builtins.toJSON`, shouldn't it? For Markdown I could think of a string generator in Nix.

**Comment by markuskowa** [comment]
> For JSON this should be easy using `builtins.toJSON`, shouldn't it? For Markdown I could think of a string generator in Nix.

`scripts/package_list` already generates the list, but I still run it manually. A Github Action, that runs it commits the new list (if a different list was generated), would be nice.

**Comment by sheepforce** [comment]
Hm, I dislike pipelines pushing and commiting. I would instead prefer to generate them as artifacts in the pipeline and link them from the README. This has the disadvantage to diverge for older commits at some point but hm, nicer than automatic commits I would say.

**Comment by markuskowa** [comment]
> Hm, I dislike pipelines pushing and commiting. 

It could either add a commit with the updated list to a PR or be triggered once a PR is merged. The latter would be less intrusive for the PR workflow.

**Comment by sheepforce** [comment]
Hm, yes but it would require the pipeline to be allowed to push to `master`. Any push will require a bot account or API key and secret management.

**Comment by markuskowa** [comment]
So, the spell check should now create less noise.
I will see if I can come with an idea for GH action that can manage such an update task without being annoying (it needs to be easier and simpler than it is now).

**Pull request merged**
