### PR TITLE
cclib: 1.7.2 -> 1.8

### PR DESCRIPTION
**Pull request by berquist**
Closes https://github.com/Nix-QChem/NixOS-QChem/issues/345

### CODE REVIEW

**Review by sheepforce — CHANGES_REQUESTED** [review]
Please update the hash of the `src` (`sha256-Eren7YGR8C+hIyDb3IMFRu4WFei0c349dm80Yiq71SE=`). When keeping to old hash you will actually still build 1.7.2.

**Comment by markuskowa** [comment]
It actually fails in the test phase:
```
======================================================================
ERROR: cclib (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: cclib
Traceback (most recent call last):
  File "/nix/store/pkj7cgmz66assy7l18zc7j992npb41nx-python3-3.10.12/lib/python3.10/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/nix/store/pkj7cgmz66assy7l18zc7j992npb41nx-python3-3.10.12/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/build/cclib-1.8/cclib/__init__.py", line 24, in <module>
    from cclib import parser
  File "/build/cclib-1.8/cclib/parser/__init__.py", line 40, in <module>
    from cclib.io.ccio import ccopen
  File "/build/cclib-1.8/cclib/io/__init__.py", line 11, in <module>
    from cclib.io.cjsonwriter import CJSON as CJSONWriter
  File "/build/cclib-1.8/cclib/io/cjsonwriter.py", line 14, in <module>
    from cclib.io import filewriter
  File "/build/cclib-1.8/cclib/io/filewriter.py", line 23, in <module>
    from cclib.bridge import makeopenbabel
  File "/build/cclib-1.8/cclib/bridge/__init__.py", line 28, in <module>
    from cclib.bridge.cclib2horton import makehorton
  File "/build/cclib-1.8/cclib/bridge/cclib2horton.py", line 20, in <module>
    from iodata.orbitals import MolecularOrbitals
ModuleNotFoundError: No module named 'iodata.orbitals'
```

**Comment by markuskowa** [comment]
I think the `iodata` package we have in nixpkgs is probably mismatched (0.1.7) while cclib wants 1.0.0a?

**Comment by markuskowa** [comment]
I gave it a try with a newer iodata, but cclib still fails with an error: `ModuleNotFoundError: No module named 'PyQt4'`.

I does not look like, there is an easy fix right now. I am going mark theodore and cclib broken for now on master.
We have theodore in the latest stable release (23.05). I would recommend to use that for now, until a fix comes along. 

We can leave this PR open as a draft.

**Comment by sheepforce** [comment]
Isn't PyQt4 deprecated? I think the Qt4 infrastructure has been deprecated in nixpkgs, now. PyQt5 and PyQt6 are both available in Nixpkgs. @berquist do you know if cclib will soon migrate to a maintained PyQt version? PyQt4 seems to be used in only one place? https://github.com/search?q=repo%3Acclib%2Fcclib%20pyqt&type=code

**Comment by berquist** [comment]
Thanks for the poke.  That code is dead but I'm not sure when exactly the next release will be cut.  I put `doCheck` back again in the meantime.

**Pull request closed without merging**
